### ISSUE TITLE
Hide Packages & releases

### ISSUE THREAD

**Issue by verma-kunal** [Prasundas99/Screen-Recorder-Electron-Based-Desktop-App#8]
Suggested to hide packages & releases if not being used in the project/repo

![Screenshot 2021-06-11 at 7 07 26 PM](https://user-images.githubusercontent.com/72245772/121694999-44c64500-cae8-11eb-90c1-25489233ea9b.png)

**Comment by Prasundas99** [comment]
Okay sure I didn't knew this feature is there Thank you
